dist: current_dir #указывает где собирать проект
moveTo: prod_dir #указывает куда копировать проект
stages:
  prebuild:
    instructions:
      - pwd
      - ls
      - ifconfig
  build:
    instructions:
      - ls
      - mvn package
  afterbuild:
    instructions:
      - echo 'suka mlya'

